print ("Online virtual machine setup wizard")
print ("\nThis wizard will guide you through the installation of an online virtual machine")
start1 = input("Press [ENTER] key to start")
print ("Select operating system")
print ("SNU comes with many operating systems to try out. Choose one from a category below:")
loopThis = str("forever")
while (loopThis == "forever"):
    print ("[::] Windows")
    print ("(*) Apple")
    print (">%> Linux")
    print ("BSD BSD")
    seL1 = str(input("Type in the ASCII art to select"))
    if (seL1 == "[::]"):
        print ("Windows based")
        print ("Select a version of Microsoft Windows")
        print ("Windows 1.00            [ID: A100000]")
        print ("Windows 1.01            [ID: A100100]")
        print ("Windows 1.02            [ID: A100200]")
        print ("Windows 1.03            [ID: A100300]")
        print ("Windows 1.04            [ID: A100400]")
        print ("Windows 2.00            [ID: A100500]")
        print ("Windows 2.01            [ID: A100600]")
        print ("Windows 2.02            [ID: A100700]")
        print ("Windows 2.03            [ID: A100800]")
        print ("Windows 2.04            [ID: A100900]")
        print ("Windows 2.10            [ID: A101000]")
        print ("Windows 3.0             [ID: A101100]")
        print ("Windows 3.1             [ID: A101200]")
        print ("Windows NT 3.1          [ID: A101300]")
        print ("Windows 3.2             [ID: A101400]")
        print ("Windows NT 3.11         [ID: A101400]")
        print ("Windows NT 3.51         [ID: A101500]")
        print ("Windows NT 4.0          [ID: A101600]")
        print ("Windows 95              [ID: A101700]")
        print ("Windows 95 SP1          [ID: A101800]")
        print ("Windows 95 SP2          [ID: A101900]")
        print ("Windows 95 SP3          [ID: A102000]")
        print ("Windows 98              [ID: A102100]")
        print ("Windows 98 SP1          [ID: A102200]")
        print ("Windows 98 SP2          [ID: A102300]")
        print ("Windows 98 SP3          [ID: A102400]")
        print ("Windows 2000            [ID: A102500]")
        print ("Windows 2000 SP1        [ID: A102600]")
        print ("Windows 2000 SP2        [ID: A102700]")
        print ("Windows 2000 SP3        [ID: A102800]")
        print ("Windows 2000 SP4        [ID: A102900]")
        print ("Windows ME              [ID: A103000]")
        print ("Windows XP              [ID: A103100]")
        print ("Windows XP SP1          [ID: A103200]")
        print ("Windows XP SP2          [ID: A103300]")
        print ("Windows XP SP3          [ID: A103400]")
        print ("Windows Server 2003     [ID: A103500]")
        print ("Windows Server 2003 R2  [ID: A103600]")
        print ("Windows Vista           [ID: A103700]")
        print ("Windows Vista SP1       [ID: A103800]")
        print ("Windows Vista SP2       [ID: A103900]")
        print ("Windows Server 2008     [ID: A104000]")
        print ("Windows Server 2008 R2  [ID: A104100]")
        print ("Windows 7               [ID: A104200]")
        print ("Windows 7 SP1           [ID: A104300]")
        print ("Windows Server 2012     [ID: A104400]")
        print ("Windows 8               [ID: A104500]")
        print ("Windows 8.1             [ID: A104600]")
        print ("Windows Server 2016     [ID: A104700]")
        print ("Windows Server 2019     [ID: A104800]")
        print ("Windows 10 B1507        [ID: A105000]")
        print ("Windows 10 B1511        [ID: A105100]")
        print ("Windows 10 B1607        [ID: A105200]")
        print ("Windows 10 B1703        [ID: A105300]")
        print ("Windows 10 B1709        [ID: A105400]")
        print ("Windows 10 B1803        [ID: A105500]")
        print ("Windows 10 B1809        [ID: A105600]")
        print ("Windows 10 B1903        [ID: A105700]")
        winIDSel = str(input("Enter an ID to continue: "))
        if (winIDSel == "A100000"):
            print ("Windows 1.0 Premiere edition Setup")
            print ("Choose a color mode: ")
            print ("VGA (1)")
            print ("Black and White (2)")
            DisplayTypeMachine1 = str("Null")
            colodis = int(input("Enter the ID you want: "))
            if (colodis == 1):
                DisplayTypeMachine1 == str("VGA")
            if (colodis == 2):
                DisplayTypeMachine1 == str("Black & White")
            print ("Windows 1.0 Premiere edition Setup")
            print ("Choose an amount of RAM: ")
            RAMInKilobytesM1 = int(input("Select an amount in Kilobytes between 80 and 4096: "))
            if (RAMInKilobytesM1 > 4096):
                print ("The amount of RAM you chose is invalid. Please select a value between 80 and 10240")
            if (RAMInKilobytesM1 < 80):
                print ("The amount of RAM you chose is invalid. Please select a value between 80 and 10240")
			print ("You selected " + str(RAMInKilobytesM1) + " KB of RAM")
			cont1 = input("Press [ENTER] key to continue setup")
			print ("Windows 1.0 Premiere Edition Setup")
			print ("Choose the screen resolution: ")
			print ("160x240 (1)")
			print ("320x240 (2)")
			resID = str(input("Enter the preferred ID: "))
			if (resID == "1"):	
				print ("You chose 160x240 resolution")
				trueRes = str("160x240")
			if (resID == "2"):
				print ("You chose 320x240 resolution")
				trueRes = str("320x240")
			print ("Windows 1.0 Premiere Edition Setup")
			print ("Choose the amount of disk space")
			machine1DiskKB = int(input("Enter an amount between 600 and 10240"))
			if (machine1DiskKB > 10240):
				print ("That is too much disk space. Please select a lower amount")
			if (machine1DiskKB < 600):
				print ("That is insufficient disk space. Please select a higher amount")
			print ("You selected " + str(machine1DiskKB) + " KB of Disk space")
			cont1 = input("Press [ENTER] key to continue")
			print ("Windows 1.0 Premiere Edition Setup")
			print ("Choose a disk type: ")
			print ("HDD (1)")
			print ("SSD (unavailable)")
			diskTypID = int(input("Enter an ID to continue: "))
			diskType = str("Hard Disk Drive")
			cont1 = input("Press [ENTER] key to continue")
			print ("Windows 1.0 Premiere Edition setup")
			print ("Select an amount of Floppy Drives")
			print ("1 (1)")
			print ("2 (2) (recommended)")
			print ("3 (3)")
			print ("4 (4)")
			print ("5 (5)")
			floppyCountID = int(input("Enter an ID to continue: "))
			if (floppyCountID > 5):
				print ("Too many floppy drives selected")
				print ("Defaulted to 2")
				floppyDriveCount = int(2)
			if (floppyCountID < 1):
				print ("Too few floppy drives selected")
				print ("Defaulted to 1")
				floppyDriveCount = int(1)
			print ("Setup summary")
			print ("Do these settings look right? ")
			print ("\nOperating system: Windows 1.0 Premiere Edition")
			print ("Color type: " + str(DisplayTypeMachine1))
			print ("RAM: " + str(RAMInKilobytesM1) + " KB")
			print ("Screen resolution: " + str(trueRes))
			print ("Disk space: " + str(machine1DiskKB) + " KB")
			print ("Disk type: " + str(diskType))
			continue1 = input("Press [ENTER] to confirm")
			loopThis = "never"
			setupSuccessful = input("Setup was successful!\nPress [ENTER] key to continue")
        if (winIDSel == "A101000"):
print ("Congratulations!\n\nYour virtual machine has been successfully set up!")
noMore = input("Press [ENTER] to continue")
'''
select an edition
'''
# notes
'''
Add options to swap between editions
choose betas from between each option
Linux trees
'''